name: rces
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7    # Python version 3.7
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - matplotlib    # 2D plotting library
    - pandas        # Labeled array library
    - seaborn       # Statistical visualizations